### ISSUE TITLE
Adding exemptLabels configuration option

### ISSUE THREAD

**Issue by Ben3eeE** [dessant/lock-threads#1]
Thank you for making the lock-threads bot :bowing_man: This looks like a great bot that we are [planning to add to the Atom org](https://github.com/atom/atom/pull/17041). One problem we are having [that came up while reviewing the PR](https://github.com/atom/atom/pull/17041#issuecomment-376695991) is that there is no way to exempt certain labels from being locked.

We close issues with the `help-wanted` label to clearly communicate that this is not something that the maintainers will have time to work on but would be interested in adding to Atom if someone from the community wants to help out. Because we close these issues unresolved with the `help-wanted` label we would also like the bot to not lock these issues so the community can continue their discussion in the issue.

We would be happy to submit a pull request to add an `exemptLabels` configuration option that would work similarly/the same way as [the probot/stale bot](https://github.com/probot/stale) `exemptLabels` config. I just wanted to first open an issue to ask if this is something that you would accept and to hear if you have any thoughts on it.

**Comment by dessant** [comment]
Awesome! I've released an update using Atom. :yum: You should be able to set `exemptLabels` just like in Stale.

**Comment by Ben3eeE** [comment]
Thank you so much!! :bowing_man:
