### ISSUE TITLE
Lock bot not working after being installed in repo

### ISSUE THREAD

**Issue by iansu** [dessant/lock-threads#10]
We installed both Stale and Lock bot in the Create React App repo a couple of months ago. The Stale bot has been working fine but the Lock bot has yet to do anything. I believe we have it configured correctly. How can I troubleshoot this? Thanks.

**Comment by dessant** [comment]
Please check if the app is enabled for the repository by visiting the app installation. I think it was initially enabled only for https://github.com/facebook/react-native (though the config is missing from the repo).

https://github.com/organizations/facebook/settings/installations

**Comment by iansu** [comment]
Unfortunately I am not a member of the Facebook organization so I can't access that page. @gaearon can you verify that Lock bot was installed in the Facebook org?

**Comment by trickdaddylatty** [comment]
Rooting fun

**Comment by trickdaddylatty** [comment]
Locbot please

**Comment by dessant** [comment]
I have checked and the Lock app does not have access to https://github.com/facebook/create-react-app, make sure to enable repository access on the configuration page of the installation.

**Comment by iansu** [comment]
Thank you. I'll do that.
