### ISSUE TITLE
Special request

### ISSUE THREAD

**Issue by anoosi** [dessant/lock-threads#12]
Hi
i have some problems and i want special feature
please this my mail anas92002@gmail.com
i can make a good donate for that
thanks

**Comment by dessant** [comment]
I'm sorry but this is not how the project is maintained. If you have a feature request, please submit it here.

**Comment by anoosi** [comment]
it's just special
and i need your mail for a work

**Comment by dessant** [comment]
My email is on my GitHub profile, though I am not available for hire.
