### ISSUE TITLE
Option to allow adding references to locked issues?

### ISSUE THREAD

**Issue by jay** [dessant/lock-threads#15]
I would like to allow references in issues after they're locked. For example we have this locked issue curl/curl#2787 and I just referenced it in curl/curl#4758 but in the locked issue there's no reference to the new issue.

**Comment by dessant** [comment]
I think that's just how GitHub works, future mentions are not shown on locked threads. You could submit a feature request to GitHub, but I think this is done on purpose to prevent appending additional comments to a locked thread by naming an issue with your message, and referencing the locked thread from it.

**Comment by jay** [comment]
Ok I will follow up with them. Thanks
