### ISSUE TITLE
Private repos?

### ISSUE THREAD

**Issue by Martii** [dessant/lock-threads#27]
Hello there. Thanks for this awesome action... did have a question about private repos though.

When I first encountered this project I tested it out in a private repo and got the very first *(last in list)* entry:

<a href="https://user-images.githubusercontent.com/114709/126698055-794cffa5-9e64-4064-9cbd-13500aa75e98.png"><img alt="Private repo workflow run" title="Click to enlarge..." src="https://user-images.githubusercontent.com/114709/126698055-794cffa5-9e64-4064-9cbd-13500aa75e98.png" width="156" height="30"></a>

So I implemented this at https://github.com/OpenUserJS/OpenUserJS.org/blob/master/.github/workflows/lock.yml where [it works great](https://github.com/OpenUserJS/OpenUserJS.org/actions) and mirror any changes from the private repo to our public GH organization repo.

However you might see in the private repo screen capture it only ran once. GitHub has started to email me around the 8th of June, 2021, every day, telling me it has failed even though it failed the very next day on the private repo.

Is there a configuration option to let this work again on private repos or am I just out of luck?

Thanks again.

**Comment by dessant** [comment]
I see the workflow runs are rather old, has it still failed in the last few days? The action is expected to work in private repos, could you share the error you get from the logs of a recently failed run?

**Comment by Martii** [comment]
> I see the workflow runs are rather old, has it still failed in the last few days?

April 28th, 2021 is the first success and every day after it has failed.

> ... could you share the error you get from the logs of a recently failed run?

Didn't realize I could click "Lock Threads".

2nd run failure is:

```
dessant/lock-threads@v2 is not allowed to be used in Martii/*clipped*. Actions in this workflow must be: within a repository owned by Martii.
```

... most recent error is:

```
dessant/lock-threads@v2 is not allowed to be used in Martii/*clipped*. Actions in this workflow must be: within a repository owned by Martii.
```

The repo is definitely owned by me otherwise I wouldn't be here with this issue. :smile_cat:

**Comment by dessant** [comment]
It looks like this is a bug or missconfiguration of GitHub action, not an issue with this action, but I don't have any idea why you might be getting that error.

**Comment by dessant** [comment]
Searching for a portion of the error lead to this: https://github.community/t/checkout-v2-error-actions-in-this-workflow-must-within-a-repository-owned-by-organization/136315

Try going through your repo and account settings again, you must have changed something that is causing the failure.

**Comment by Martii** [comment]
> Try going through your repo and account settings again

Will do.

> you must have changed something that is causing the failure.

It's been idle except for when you did https://github.com/dessant/lock-threads/releases/tag/v2.1.1 and I updated OUJS at the same time. No changes to anything Account wise or private repo wise.

> It looks like this is a bug

Will double check those settings... but I have a feeling it is a GitHub gremlin.

**Comment by Martii** [comment]
Interesting... GitHub changed my permissions on the private repo :boom: to local only and they also seem to have a gremlin on orgs too with greyed out specified actions:

<a href="https://user-images.githubusercontent.com/114709/126704086-7ce10a0d-36f1-4714-9eca-d3de16e2445c.png"><img alt="Init org settings" title="Click to enlarge..." src="https://user-images.githubusercontent.com/114709/126704086-7ce10a0d-36f1-4714-9eca-d3de16e2445c.png" width="140" height="53"></a>

Will play around with the private repo settings again to see if it runs in next few hours.

> Try going through your repo and account settings again

Not nice for GitHub to change my settings without my consent and the org disabling specified actions is just as disconcerting. :smile_cat:

**Comment by Martii** [comment]
Different error this time with the appended message at the comment above:

```

Error : .github#L1
dessant/lock-threads@v2 is not allowed to be used in Martii/*clipped*. Actions in this workflow must be: within a repository owned by Martii, created by GitHub or verified in the GitHub Marketplace.
```

Says you aren't in the Marketplace which was verified again about 8 hours ago that you were. More GitHub gremlins?

Will try with yet another settings but it probably won't be staying that way since I don't want any actions to run *(that's a security issue)*... get to wait 24 hours for it to run since I'm not touching the repo data itself.

---

**Comment by Martii** [comment]
@dessant 

### Filtering (final)

<a href="https://user-images.githubusercontent.com/114709/127086583-2487c8ef-fc3f-40d7-a84d-70365113c5b4.png"><img alt="Temporary All Actions Result" title="Click to enlarge..." src="https://user-images.githubusercontent.com/114709/127086583-2487c8ef-fc3f-40d7-a84d-70365113c5b4.png" width="154" height="50"></a>


### Hypothesis

> The action is expected to work in private repos,...

* :heavy_check_mark: Allow all actions
    Any action can be used, regardless of who authored it or where it is defined.
* :heavy_check_mark: Disable Actions
    The Actions tab is hidden and no workflows can run.
* :heavy_minus_sign: Allow local actions only
    Only actions defined in repository within Martii can be used.
* Allow select actions
    * :heavy_minus_sign: Allow actions created by GitHub
    * :x: Allow Marketplace actions by verified creators
    
    
Legend:
| Test Result | Symbol |
|---|---| 
| UNTESTED | :heavy_minus_sign: |
| PASS | :heavy_check_mark: |
| FAIL | :x: |

### Summary:

> ... not an issue with this action...

1. According to GitHub you don't have the badge for verified creator even though their filter QSP shows you in [a query](https://github.com/marketplace?type=actions&verified_creator=true&query=lock+threads+). :-1: Not entirely sure how you get verified properly at this time... good luck with this on your issue with this action. :+1:

2. Will only run in insecure mode for a private repository *(allow any action)* :-1:


Note(s):

> Note: The Allow specified actions option is only available in public repositories with the GitHub Free, GitHub Pro, GitHub Free for organizations, or GitHub Team plan.

... from [here](https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/disabling-or-limiting-github-actions-for-a-repository#allowing-specific-actions-to-run). Not entirely true but close enough with not showing [filter list](https://user-images.githubusercontent.com/114709/126705495-bd07f0d6-bb72-4a6d-acc7-6c22ad12e211.png) at this time.

* Did not test PAT yet but will in the future. GITHUB_TOKEN is partiallly usable in certain unsafe repository modes.

Thanks for the pointers on where to hunt down the issues applicable to GitHub and this Action. :smiley:

**Comment by dessant** [comment]
Thanks for the detailed analysis! It seems the verified status is not yet available for user accounts, I'll apply when it becomes possible.

https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/applying-for-publisher-verification-for-your-organization
https://github.community/t/how-to-become-verified-creator-of-a-github-action/116009/5
