### ISSUE TITLE
Update Node.js runtime

### ISSUE THREAD

**Issue by arkon** [dessant/lock-threads#36]
Getting this during action runs:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: dessant/lock-threads

**Comment by dessant** [comment]
Please update to Lock Threads v4.0.0 to fix the issue.

```yaml
    steps:
      - uses: dessant/lock-threads@v4
```
