### ISSUE TITLE
`set-output` is deprecated

### ISSUE THREAD

**Issue by mister-ben** [dessant/lock-threads#37]
`set-output` will be disabled in May 2023.

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by dessant** [comment]
Please update to Lock Threads v4.0.0 to fix the issue.

```yaml
    steps:
      - uses: dessant/lock-threads@v4
```
