### ISSUE TITLE
Define activity

### ISSUE THREAD

**Issue by Roxedus** [dessant/lock-threads#39]
Im looking into using this in conjunction with the actions/stale actions, to further lock issues after being stale. 

So I wonder Is bot comments/actions counted as activity?

**Comment by dessant** [comment]
> So I wonder Is bot comments/actions counted as activity?

I think they are counted as activity, though you can test it just to be sure with the `updated` search qualifier on GitHub.

https://github.com/dessant/lock-threads#how-are-issues-and-pull-requests-determined-to-be-inactive
