### ISSUE TITLE
log-output: true not logging output

### ISSUE THREAD

**Issue by alessbell** [dessant/lock-threads#40]
Hi there, thanks for your work on this action! We've been using it in the https://github.com/apollographql/apollo-client repo and it locked a bunch of PRs and issues off the bat 🙏 

After a few hours though, I noticed it hit a plateau of [around ~10% of existing closed issues and PRs](https://github.com/search?q=repo:apollographql/apollo-client%20is:locked&type=code). I've tried using `exclude-issue-created-after`/`exclude-pr-created-after` to limit the number that were being initially fetched, then set `process-only: 'issues'` and finally turned on log output, but I'm not seeing any output ([example run](https://github.com/apollographql/apollo-client/actions/runs/4165896757/jobs/7209522558)). Would appreciate any guidance here, thanks!

**Comment by alessbell** [comment]
After running the script locally, I can see the search returning valid PRs + issues that still need to be locked. I have to assume on CI the search is returning nothing for whatever reason since all logging statements seem to be inside the loop over `results`, so maybe even logging `N issues and/or PRs were found` before the loop would be helpful signal.

**Comment by alessbell** [comment]
The issue turned out to be a GH label that contained whitespace 🥲 Looks like it needs to be passed with double quotation marks to the search endpoint to prevent this; as is, the search was returning no issues or PRs. I just removed the whitespace from the label and everything is back to normal. Closing, thanks!

**Comment by dessant** [comment]
Hi @alessbell and @jameslamb, Lock Threads 5.0.1 now supports filtering by labels with spaces, putting the label name in nested quotes is no longer needed. Version 5 also locks closed discussions by default, so make sure to update the workflow to preserve the old behavior.

```yaml
    steps:
      - uses: dessant/lock-threads@v5
        with:
          process-only: 'issues, prs'
```

**Comment by jameslamb** [comment]
Thanks for the fix and the `@`!

Should I still expect the nested quotes to work, though?

**Comment by dessant** [comment]
@jameslamb, quotes around labels are stripped when the input parameters are parsed, so your configuration should continue working if you update to v5. Though I've only added quote stripping because I've noticed a couple of projects using nested quotes as a workaround in v4, and at some point it would be good to no longer preventively strip quotes, because it could cause unexpected issues.
