### ISSUE TITLE
Question: is it possible to lock silently?

### ISSUE THREAD

**Issue by tvdijen** [dessant/lock-threads#41]
Hi!

I'm new to this action and started using this only yesterday.
It became quite noisy because every lock triggered a notification in Github.
Is it possible to suppress this? Or is this because I set a `issue-comment` and would it be silent without the comment?

Thanks!

**Comment by tvdijen** [comment]
I was thinking maybe a config setting `unsubscribe` could be added that would unsubscribe everyone from the issue/pr before locking it?

**Comment by dessant** [comment]
Hi, the action can't unsubscribe people from events, but I think the notification is created by the comment the action is posting, you could remove those from your config to avoid getting emails about old issues.
