### ISSUE TITLE
Release `v5` which runs on node20

### ISSUE THREAD

**Issue by trivikr** [dessant/lock-threads#44]
As per [GitHub Actions: Transitioning from Node 16 to Node 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)

> Starting October 23rd, workflows containing actions running on Node 16 will display a warning to alert users about the upcoming migration.

The `dessant/lock-threads@v4` uses node16 which is [end-of-life](https://github.com/nodejs/Release/#end-of-life-releases).
https://github.com/dessant/lock-threads/blob/be8aa5be94131386884a6da4189effda9b14aa21/action.yml#L104

Release `dessant/lock-threads@v5` which runs on node20?

**Comment by trivikr** [comment]
Commit which had upgraded from node 12 to 16 in v4 https://github.com/dessant/lock-threads/commit/38e918558115222435d26c0639870cdbe3572929

**Comment by dessant** [comment]
Version 5 has been published.
