### ISSUE TITLE
[Feature Request] Option to disable notifications

### ISSUE THREAD

**Issue by simurai** [dessant/lock-threads#6]
Would it be possible to add an option to disable sending a GitHub notification when an issue gets locked? Not sure if Probot supports that feature?

It's not a big issue for people that get GitHub notifications by email since they can create a filter. But for [Web Notifications](https://github.com/notifications) having all the locked issues show up again makes it quite noisy.

![screen shot 2018-06-07 at 8 24 25 am](https://user-images.githubusercontent.com/378023/41071179-7def044a-6a31-11e8-95d4-53fe3eb5ba47.png)

**Comment by dessant** [comment]
The notifications are created while posting comments, I think there is no good way for the comment author to prevent these notifications. The app can be [configured](https://github.com/atom/atom/blob/a3e5fc0be13d821699496e0f6d076c386361e29c/.github/lock.yml#L5) to skip posting comments, I'd check in with @lee-dohm about it. Though they were in favor of explaining the reason of the lock and mentioning further actions that could be taken by users.

**Comment by simurai** [comment]
Thanks for the super 🚀 fast answer.

Ok, I see. It's the comment that actually sends the notifications. And comments without a notification are probably not allowed with the GitHub API.

> Though they were in favor of explaining the reason of the lock and mentioning further actions that could be taken by users.

Yeah, I can see the benefit of adding a comment to explain why it got locked. 👍

**Comment by dessant** [comment]
A feature request could also be rised internally for ignoring notifications from certain users and apps, like on social networks. This is currently possible only by blocking users, but you can't block apps.

**Comment by simurai** [comment]
Or it could also be something that the Web notifications can improve. Like allowing to "mute" certain notifications, like you can mute tweets that contain certain words.

**Comment by dessant** [comment]
Yeah, such advanced filtering would be awesome. :dancer:
