### ISSUE TITLE
Bot locking "as resolved"

### ISSUE THREAD

**Issue by batpigandme** [dessant/lock-threads#7]
Hi,

Love your probots!

It was just pointed out that the lock bot is locking threads "as resolved" (e.g. see [here](https://github.com/tidyverse/dplyr/issues/2773)). 
![image](https://user-images.githubusercontent.com/831732/41792576-53f127f2-7627-11e8-86e8-c90014294c51.png)

Is there a way to reconfigure so it's locking without a reason, as in the example (and as I modified, above)? The `lock.yml` for that repo is [here](https://github.com/tidyverse/dplyr/blob/master/.github/lock.yml). I don't think I've configured it specifically for "resolved" anywhere, but could easily be missing something.

Thanks for your help.
Mara

**Comment by dessant** [comment]
Hi! This change was introduced in https://github.com/dessant/lock-threads/pull/3 and it is not configurable at this time.

**Comment by batpigandme** [comment]
😳 so sorry, thought I searched issues _and_ PRs! Awesome, thanks so much!

**Comment by dessant** [comment]
@batpigandme, please use `setLockReason: false` to stop setting the locking reason. Thanks for filing this issue, and sorry for the inconveniece. :dog:

**Comment by batpigandme** [comment]
Awesome! Thanks so much 😊
